import Home from "./page";

export const metadata = {
  title: "Hello World",
  description: "Generated by Next.js",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body>
        <Home />
      </body>
    </html>
  );
}
